coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  deletions: false

github:
  require_ci_to_pass: true
